apiVersion: v1
kind: Pod
metadata:
  name: streamlite
  labels:
    app: streamlite
spec:
  containers:
    - name: streamlite
      image: elazarmeijers/streamlit-test:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      